### PR TITLE
New maps and updates to f_nrge data

### PR DESCRIPTION
**Pull request by elbfox**
This PR includes fixes for properties variable in f_nrge from Sam. I converted all instances of RData to .csv because I can't open any of the .RData files on my computer anymore for some reason. I upgraded my version of R and that didn't solve. 

added data.table and dplyr packages to server.R too

### CODE REVIEW

**Comment by elbfox** [comment]
@sythel please review, I'm hopeful that this addresses some of the inconsistencies in #151 and #153, but it would be helpful to have this version live to be able to make a call to pull the multi-dam stuff tomorrow if I have to.

**Comment by sythel** [comment]
reviewing

**Comment by sythel** [comment]
this wouldn't fix server as server is using WSM.R not WSM_graphs_test.R i will add decision fix commit incoming

**Comment by sythel** [comment]
will launch this branch to server

**Pull request merged**
