### PR TITLE
pull in important master changes to branch

### PR DESCRIPTION
**Pull request by sythel**
pull in master changes to fix server.R

### CODE REVIEW

**Comment by elbfox** [comment]
Is this something you need me to review? There are a few files marked as conflicting, but perhaps that's not a problem since all of the files get updated in GraphChecking branch. I'm making a few more changes to that one, still. 

When this is all merged, can you update the 'live' web version (http://dams-mcda.gsscdev.com/dams_mcda_wrapper/) too? I'm hoping we can get a test version together by Monday...do you think that is reasonable?

**Comment by sythel** [comment]
no approval needed, for personal branch

**Comment by sythel** [comment]
> When this is all merged, can you update the 'live' web version (http://dams-mcda.gsscdev.com/dams_mcda_wrapper/) too?

sure

> I'm hoping we can get a test version together by Monday...do you think that is reasonable?

@elbfox depend on whats needed for test version

**Comment by elbfox** [comment]
Bare minimum I want to make sure that the front page "Step 1: Start Here" and map page "Step 2: View Map" are updated with my recent changes, with the slider bars showing the 1-100% (that was an adjustment I made today or yesterday). Also, I would like the results pages to have the raw results (slider bar inputs graphed) visible. 

Ideally, we would have the graphs printing out, too, with downloadable results (so, for instance, someone could toggle around and get some kind of a result). All of this needs to be done and working by the last week in September, but the bare minimum is what we need by Monday.

**Comment by sythel** [comment]
graphs might be a stretch for monday, hard to say right now but also short on time

**Pull request merged**
