### PR TITLE
DO NOT APPROVE RIGHT AWAY, but launch live ASAP

### PR DESCRIPTION
**Pull request by elbfox**
This branch represents the MCDA only with no MOGA scenario information whatsoever. I pulled out multi-dam and coordinated dam references, maps, and multi-dam functionality besides aggredated single-dam output. This branch should live separately from the rest of the branches (or however this works), but needs to be LIVE ASAP TOMORROW, 10/2/2019 for testing and review by Sharon and FOD colleagues. 

We had to go ahead without this MOGA/coordinated multi-dam output for the workshop, but we do want it in the final DDC version of the model. 

Is it possible to have this live and on a real site, not a dev site, by afternoon tomorrow?

### CODE REVIEW

**Comment by sythel** [comment]
@elbfox what do you mean by real site (not dam-mcda.gsscdev.com?)

**Comment by elbfox** [comment]
> @elbfox what do you mean by real site (not dam-mcda.gsscdev.com?)

Sorry for just getting back to you now. Isn't the current site a dev site? Last time we used a dev site it would crash with too many people using it. Is that a different problem? 

Is it possible to do a version release of just this branch? (that may be a different, later problem for after the workshop). Basically what I'm asking is if this branch could be made live and workable for ~10 people at a time tomorrow starting at 8:30am, when our workshop begins.

**Comment by elbfox** [comment]
FYI: all of the conflicting files are intentionally conflicting (i.e., they are all missing references to num_scenarios, NormalizedMatrix, and multi-dam anything). It might be that a PR is not the way to handle this, given the nature of the conflicts, so I would really appreciate your input, @sythel.

**Comment by sythel** [comment]
branch MCDA_Only_No_MOGA live

**Comment by elbfox** [comment]
> @elbfox branch MCDA_Only_No_MOGA live

live version doesn't generate results, causes reload dialogue box to pop up

**Comment by sythel** [comment]
relaunched with fix

**Comment by elbfox** [comment]
image
Fig 1 individual dam results does not print (additional info: I did use 100% fish prefs for all sites, but that shouldn't matter, since Fig 1 combined results with aggregated decision alternatives/scores for all dams prints out fine).

**Comment by sythel** [comment]
> Fig 1 individual dam results does not print

trying to replicate now

**Comment by elbfox** [comment]
Also, not a problem for us tomorrow, but the mobile version of the site doesn't let me scroll down (using iPhone and Safari). It was awkward on iPhone/Safari in the past (like waaay back in March for the student test workshop and last version of this app) but functional. It does load on the iPhone/Safari page but since I can't scroll down, I can't actually use the slider bars in the mobile version. I can add this as a separate issue. I did try Safari on a Macbook and that works fine.

**Comment by sythel** [comment]
think its fixed now + progress trackers now follow screen

**Comment by sythel** [comment]
> Also, not a problem for us tomorrow, but the mobile version of the site doesn't let me scroll down (using iPhone and Safari). It was awkward on iPhone/Safari in the past (like waaay back in March for the student test workshop and last version of this app) but functional. It does load on the iPhone/Safari page but since I can't scroll down, I can't actually use the slider bars in the mobile version. I can add this as a separate issue. I did try Safari on a Macbook and that works fine.

these work for android, and just tested on iphone 10

**Comment by elbfox** [comment]
> these work for android, and just tested on iphone 10

@sythel it doesn't work on iPhone 7 but is that considered very old now? It's the only mobile device I have to test on (because it's mine).

**Comment by sythel** [comment]
seems iphone 7 should have iOS 13 so it should be the same as iphone 11

**Comment by elbfox** [comment]
Also, could you add axis lines to all figures that don't already have them? 

Sharon says: Still not getting any data for end of individual page download [name of dam] button (see attached for West Enfield - checked Medway too and same thing - didn't check all)

 File names for almost all downloads on Individual pages say West Enfield in them - I am pretty sure the data match the individual dams, not West Enfield, but I didn't check all - everything except Download [Name of Dam] button. Users won't be able to tell which table refers to which dam if they go through and download them one at a time while looking through the results and then go back and open them later. Is there a plan to have a bulk download button post-workshop?

**Comment by elbfox** [comment]
> seems iphone 7 should have iOS 13 so it should be the same as iphone 11

I have not updated, so that's probably the issue. Thanks for checking! I think we're all set with the mobile device issue.  Have you tested using mulitple devices at one time in group mode?

**Comment by elbfox** [comment]
> I have not tested simultaneous running.

Sharon and I will do this later today (~3pm?)

> i just made user elbf a admin on the site so you can add/remove/name groups

Can you please make Emmafo an admin instead? I didn't save the user elbf and I have no idea what the password is now. 

I have a few changes to make to this version but will commit them to the active PR in 30 mins or so.

**Comment by sythel** [comment]
> Can you please make Emmafo an admin instead? I didn't save the user elbf and I have no idea what the password is now.

done

**Comment by sythel** [comment]
by design shiny server isn't great at number of connections

so the max connections recommended by shiny server is 5-20

would need shiny server pro to accommodate more instances

**Comment by elbfox** [comment]
> by design shiny server isn't great at number of connections
> 
> so the max connections recommended by shiny server is 5-20
> 
> would need shiny server pro to accommodate more instances

We will only have 9 people on at one time, so hopefully it works. Sharon and I are going to test shortly. I have to run over to another building. Is this latest commit something you can push to the live version, please?

**Comment by sythel** [comment]
latest commit on server

**Comment by sythel** [comment]
> We will only have 9 people on at one time, so hopefully it works.

I might have figured out a solution for increased connections

**Comment by elbfox** [comment]
> > We will only have 9 people on at one time, so hopefully it works.
> 
> I might have figured out a solution for increased connections
> 
> i am able to leverage our use of docker to spawn multiple shiny servers with load balancing through apache, how many server should i spawn for tomorrow? 2 or 3 ?

I actually think we are okay with one, Sharon and I are testing right now and have 9 machines using the app and generating/saving/downloading preferences. Just to be safe, could you spawn 3 servers? I have no idea what any of that means but it sounds like you have it figured out. We are testing that the averaging is working the way we think it should.

**Comment by sythel** [comment]
i will do launch atleast two

I will add one more commit to PR #176 making all tables the same theme again then will launch to server

if you have changes to merge in this PR I will add to the server relaunch

**Comment by sythel** [comment]
new version live 2 servers with load balancer

>I have no idea what any of that means but it sounds like you have it figured out
this means first visit time a user visits the site they get assigned a server out of the ones we have. 
its comparable to multiple lanes of traffic vs one
it all happens behind the scenes and hopefully its never a problem

**Comment by sythel** [comment]
after reviewing it seems the only things we may keep from this branch would be text updates from ui.R

**Comment by elbfox** [comment]
> after reviewing it seems the only things we may keep from this branch would be text updates from ui.R

I thought I also updated how we deal with the damage criterion in the Ind_NormalizedMatrix, too, but I' m not seeing it as a conflict with the master in WSM.R listed in conflicting files, so it's possible that I already fixed it. Also, we aren't going to want to keep all of the deletions I made in ui.R, but we might want to include some additions (like links). Do you have suggestions for how to best deal with this @sythel ?

**Comment by sythel** [comment]
> I thought I also updated how we deal with the damage criterion in the Ind_NormalizedMatrix, too,

yes one line is commented out.

> but we might want to include some additions (like links)

which links

> Do you have suggestions for how to best deal with this

Lets keep this PR open and use it to compare progress of the next PR #178 . 
you will want to review at changes you made on this branch and if wanted in v2.0.0 add to a new PR into branch postWorkshop or add into PR #178 itself.

commits you should review:
 b1e7624bfe1f1ddeed2ac0ab63035ad6083c1aaa
04544bf53cc91e54d92629da5decac45d0c82435
~~25a7edb8f26866cde4884824e187ce643310d26f~~ (specifically for v1.5.0)
3d04c8a2cb029540dc9c006edaffb67489c2e789

**Comment by elbfox** [comment]
> Lets keep this PR open and use it to compare progress of the next PR #178 .

Sounds good. 

> you will want to review at changes you made on this branch and if wanted in v2.0.0 add to a new PR into branch postWorkshop or add into PR #178 itself.
> 
> commits you should review:
> b1e7624
> 04544bf
> 25a7edb (specifically for v1.5.0)
> 3d04c8a

Reviewed these, small things need to stay in, commented line by line.

**Comment by sythel** [comment]
closing this branch as it was only for v1.5.0 which is a tagged version if it needs to be referenced later on

**Comment by elbfox** [comment]
May want to reopen...I'm working on adding a list of new issues right now. Sharon and I discussed keeping both app versions (with MOGA stuff and without) open, making changes to both as we go because we may need to cut the MOGA stuff for the real, final version to be hosted on the DDC portal.

**Pull request closed without merging**
