### PR TITLE
Combining Changes

### PR DESCRIPTION
**Pull request by sythel**

### CODE REVIEW

**Comment by sythel** [comment]
PR looks good to me; however it's missing f_nrge2.RData

**Comment by sythel** [comment]
change that was requested was made

**Comment by elbfox** [comment]
Thank you! I'm now viewing CombinedPreferenceOutput to check on the 100% thing

**Comment by elbfox** [comment]
Oops...looks like the whole block of individual dam tables for the results tabs got deleted from WSM_graphs_test.R in the merge. It was the second large block of code. Need that for generating decision matrix outputs (I haven't added this as an issue yet...I'm super behind on this)

**Comment by sythel** [comment]
@elbfox line 403 -> 514?

**Comment by elbfox** [comment]
Yes. I tried to add it back in just now and I've really confused my index state, so if it's easy for you to add it back in, please do.

**Comment by sythel** [comment]
its there for me; might have to fetch and pull the branch again

**Pull request merged**
