### PR TITLE
Simplify normalization

### PR DESCRIPTION
**Pull request by sythel**

### CODE REVIEW

**Comment by sythel** [comment]
output from run:
old method: c(0, 0, 0.500079936051159, 1, 0.500079936051159)c(0, 0, 0, 0, 0)c(0, 0, 0, 0, 0)c(0.13254321032179, 0.13254321032179, 0, 0, 1)c(0, 0, 0, 0, 0)c(1, 1, 1, 1, 0)c(1, 1, 1, 1, 0)c(1, 1, 1, 1, 0)c(0, 0, 0.25, 0.25, 1)c(1, 0, 0, 0, 0)c(0, 0, 0.333333333333333, 0.333333333333333, 1)c(0, 0, 0, 0, 1)c(0, 0, 0.25, 0.25, 1)c(0, 0, 0.25, 0.25, 1)
shiny_server_1  | old method col: c(0, 0, 0.500079936051159, 1, 0.500079936051159)
shiny_server_1  | new method: 000.50007993605115910.50007993605115900000000000.132543210321790.1325432103217900100000111101111011110000.250.25110000000.3333333333333330.333333333333333100001000.250.251000.250.251
shiny_server_1  | new method col: 000.50007993605115910.500079936051159

**Comment by elbfox** [comment]
Let me know when this is ready for review. If the values are the same as in GraphChecking then I'd say we're all set.

**Comment by sythel** [comment]
problem with dam_names/alternative_names but i don't think its a huge issue. ready for review

**Comment by sythel** [comment]
changes made

**Pull request merged**
