### PR TITLE
Updates to tables in results tabs

### PR DESCRIPTION
**Pull request by elbfox**
Added tables for raw pref values, raw data, normalized data values, and weighted score values.

NOTE: There is a problem here when pressing 'update' in the individual dam tabs that causes an error that closes the app. I'm not sure where it's coming from because the tables all worked when I tested it for West Enfield.

### CODE REVIEW

**Comment by elbfox** [comment]
Issue with WeightedScoreMatrix calculation...NormalizedMatrix*PrefsMatrix should work because they have the same dimensions and elements. 

NormalizedMatrix reads as an array (check: class(NormalizedMatrix)) with 3 dimensions (check: dim(NormalizedMatrix)) and yet when I go to see any individual level or row (check: NormalizedMatrix[,,1]), error says "Incorrect number of dimensions". NormalizedMatrix is just the f_nrge.Rdata. Not sure what the problem is, but it's preventing the WSM Multi-Dam calculation in this branch. I changed slightly how f_nrge was being read in because every other time I run the script it says the file cannot be found or is corrupted (which obviously isn't true because I can view NormalizedMatrix. None of these problems happen with PrefsMatrix, so I think it goes back to f_nrge.RData somehow.

**Comment by elbfox** [comment]
Appears fixed now, but f_nrge.RData doesn't source consistently for me. @sythel have you had this problem in the WSM_graphs_test.R? I only checked it because I'm trying to troubleshoot that slider bar issue #126 by back tracking. Error code indicated that the server.R script was unable to access WestEnf_DataMatrix from WSM_graphs_test.R

**Comment by sythel** [comment]
haven't had the problem; but I also don't use WSM_graphs_test.R

**Comment by sythel** [comment]
was there a package added? DT?

**Comment by elbfox** [comment]
I guess I must have added it and not saved?, because I wrote it in the code but it's not on the list of packages. Adding now and reloading app locally...

**Comment by sythel** [comment]
> I guess I must have added it and not saved?, because I wrote it in the code but it's not on the list of packages. Adding now and reloading app locally...

is the the library DT or I see 
```
library(data.table)
```
in WSM.R

**Comment by sythel** [comment]
It would be nice if we could remove individual dam generate buttons and just make one that will do all individual and the combined.

**Comment by sythel** [comment]
should i make fixes on this branch?

once they are set I would like to get this PR done ASAP so I can merge changes from my branch

**Comment by elbfox** [comment]
> should i make fixes on this branch?
> 
> once they are set I would like to get this PR done ASAP so I can merge changes from my branch

I fixed the issues that I was encountering. If you have more, please make them and merge the PR.

**Comment by elbfox** [comment]
reverted

**Comment by elbfox** [comment]
> I want to keep all table/plot rendering outside of WSM.R, please revert all changes to WSM.R

So do you not need those tables after all? I had hoped I was saving you some time, but if not that's fine, i'm still using them locally.

**Comment by sythel** [comment]
Those tables are encapsulated into one big table (AllDataMatrix inside WSM.R) so its easier to access them in a for loop. Its beneficial for development if we keep all table rendering in server.R, otherwise we have to send output context to WSM.R.

**Comment by elbfox** [comment]
I'm not completely sure I understand, but it seems cleaner/more efficient as you describe. I've taken them out of WSM.R so should be good to go.

**Comment by sythel** [comment]
closing in favor of PR #130

**Pull request closed without merging**
