### PR TITLE
Finalizing Dam Decision Support Tool

### PR DESCRIPTION
**Pull request by elbfox**
Creating a pull request to track final changes, needs review. 
Issue #192, Issue #190, and some other problem that highlights line 158 in WSM.R as a problem.

- Change from 14 criteria to 12
- Text updates (criteria definitions)

**Still working on:**

- Limitations statement
- Advanced instructions (for downloading and editing)

### CODE REVIEW

**Comment by sythel** [comment]
power outage and major system upgrades caused the sites to go down. They are up as of now.
(shiny.gsscdev.com, shiny2.gsscdev.com, dams-mcda.gsscdev.com(shiny3))

shiny.gsscdev.com (version 1 archive website)
shiny2.gsscdev.com is last updated oct 10 (most up to date)
dams-mcda.gsscdev.com is last updated oct 1

**Comment by sythel** [comment]
changes look good to me so far. 

What do we want to do for existing servers & development servers?

For a development preview site can we remove the current dams-mcda.gsscdev.com and move shiny2.gsscdev.com to it as it is more up to date version? Then we can use shiny2.gsscdev.com as the development preview domain name.

**Comment by elbfox** [comment]
Excellent, thank you for reviewing! I think your proposed solution for server/development server is good. Wrapping up text updates today, checking on other existing now.

**Comment by sythel** [comment]
dams-mcda.gsscdev.com running version tagged version 2.0.1
shiny2.gsscdev.com is new development preview server

**Comment by elbfox** [comment]
If this is OK to merge @sythel (upload files is still an issue locally/offline on this branch), then I have a list of some additional changes tomorrow that should not impact what is here in DDST_v4 branch and then I think we are all ready to go

**Comment by sythel** [comment]
Sure we can merge. I don't have time to test today for the upload issue so I will have to revisit that early next week.

**Comment by elbfox** [comment]
Thanks. I'm hoping it won't cause issue.

**Pull request merged**
